### ISSUE TITLE
Document data sources and script generating the required input data

### ISSUE THREAD

**Issue by sgreenbury** [Urban-Analytics-Technology-Platform/acbm#39]
This issue aims to document and automate where possible the set-up of required data for the pipeline. This will enable the pipeline to be run for other regions (specifically Greater London as a next case).

- [x] Add current file tree structure in `data/` path
- [x] Script to get boundaries for region
- [ ] Travel times for interzone travel #20
- [x] Consider using alternatives to OA for larger regions (e.g. make resolution as config param)
- [x] POI data (see #19)
- [x] NTS input update (see #16)

**Comment by Hussein-Mahfouz** [comment]
This is the travel time workflow I used in another project

1. Step 1: https://github.com/Hussein-Mahfouz/drt-potential/blob/main/code/routing_prep.R
2. Step 2: https://github.com/Hussein-Mahfouz/drt-potential/blob/main/code/routing_r5r.R

**Comment by sgreenbury** [comment]
From OSMOX: "west-yorkshire_epsg_4326.parquet"

**Comment by sgreenbury** [comment]
Documentation can be added in the scripts README: https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/main/scripts/README.md

**Comment by sgreenbury** [comment]
Discussion with @Hussein-Mahfouz around how to generalize the boundary and travel time inputs. Currently the geometry ID (e.g. OA or MSOA) is specified independently in each script with different logic paths.

Considerations going forward:
- Only OA and MSOA or other zone layers
- Standardizing names for columns for boundary and travel times (e.g. the input data should be relabelled and then can be validated in data processing). Aim to just use `zone_id`, `from_id`, `to_id`.

**Comment by Hussein-Mahfouz** [comment]
@sgreenbury I've tried to capture all necessary updates in this comment. We will need to make edits to both the library functions and the scripts. We can move this to a separate issue if necessary

## General

### Preprocessing script

- [ ] Decide on column names for zone_id column. this should be reflected in activity_chains, boundaries, and travel_times data. These names should work regardless of layer (OA, MSOA etc). It would then be ok to hardcode these columns in the functions/scripts and check their existence using pandera. Initial idea:
    - activity_chains: zone_id
    - boundaries: zone_id
    - travel_times: from_id and to_id
- [ ] preprocess boundary layer: Currently we load the boundary layer for the UK in each script, and filter it (see [here](https://github.com/search?q=repo%3AUrban-Analytics-Technology-Platform%2Facbm%20where_clause&type=code)). 
We need to do this once in a preprocessing script. Steps:
    - load in our boundary layer (currently OA or MSOA)
    - if boundary layer has a city column, we can use that to filter, and grab the city name from the config.
    - Otherwise we need to use another layer that can be subsetted to our desired region, and then do a spatial intersection with our boundary layer to crop out the region we want
- [ ] Spatial join: _Use variable zone_id from config instead of hardcoded OA21CD_ [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.1_assign_primary_feasible_zones.py#L60). This needs to be done for [these scripts](https://github.com/search?q=repo%3AUrban-Analytics-Technology-Platform%2Facbm+gpd.sjoin+join+path%3A%2F%5Escripts%5C%2F%2F&type=code). Alternatively, do this join once in the once in the beginning in a preprocessing script. 
- [ ] Preparing travel demand data in 3.2.2_assign_primary_zone_work:  (see [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/main/scripts/3.2.2_assign_primary_zone_work.py#L53-L161))

### Config 
- [ ] Add ["**TravDay**"] == 3] to config - see [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.2.1_assign_primary_zone_edu.py#L50). We then need to remove this filter step in all scripts


## Per script
- [ ] _scripts/2_match_households_and_individuals.py_

- [ ] _scripts/3.1_assign_primary_feasible_zones.py_
    - [ ] [add_locations_to_activity_chains()](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/src/acbm/preprocessing.py#L335). This currently uses an OA level centroid layer. It also assumes that the activity_chains layer has an id column that matches the centroid_layer.  
        - [ ] _Get location from boundary layer instead: Get centroid of boundary layer -> Join using id column_. Avoids use of extra layers
        - [ ] Decide whether to do this in a preprocessing script. It is done many times
     - [ ] Reading osm POI data: We are currently reading a static file [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.1_assign_primary_feasible_zones.py#L160)   
         - [ ] Option 1: Point the user to osmox and tell them to get their POI data from there, and describe where to add it in the acbm directory
         - [ ] Option 2: Implement cli in workflow (see #19). Save the POI layer with a generic name so it works for all scripts (i.e. not west_yorkshire_epsg_4326)
     - [ ] [get_possible_zones()](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/src/acbm/assigning/feasible_zones_primary.py#L10)
         - [ ] Add zone id columns to [schemas](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/89eaad8b6a556a761edc2ef3216373d7ece05d0e/src/acbm/assigning/feasible_zones_primary.py#L20). This should be done after deciding what the zone_id column will be called. It will reflect in all schemas
         - [ ] [_get_possible_zones()](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/89eaad8b6a556a761edc2ef3216373d7ece05d0e/src/acbm/assigning/feasible_zones_primary.py#L246) internal functions: Remove hardcoded zones and replace with either (a) a parameter from the config, or a hardcoded generic name that we decide on from the zone_id
         
- [ ] _scripts/3.2.1_assign_primary_zone_edu.py_
    - [ ] Same hardcoding issue with [add_location()](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.2.1_assign_primary_zone_edu.py#L62)
    - [ ] [fill_missing_zones()](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/src/acbm/assigning/select_zone_primary.py#L156): Reomove hardcoded OA21CD
         
- [ ] _scripts/3.2.2_assign_primary_zone_work.py_ 
    - [ ] See section on preprocessing script for preparing commuting flow data
    
- [ ] _scripts/3.2.3_assign_secondary_zone.py_
    - [ ] Replace hardcoded OA21CD [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.2.3_assign_secondary_zone.py#L107) and [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.2.3_assign_secondary_zone.py#L126)
    - [x] edit modes to use: Should be done [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/pull/48/files#diff-972cc8a1708fd5ae32af721c1d149f233bc44c6b1818b747eb9640316179a009)
    - [ ] remove hardcoded OA21CD [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.2.3_assign_secondary_zone.py#L343) and [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.2.3_assign_secondary_zone.py#L350) and [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.2.3_assign_secondary_zone.py#L369)
    - [ ]          - [ ] Same hardcoding issue with [add_location()](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/0aac6908c7474e02fd9bd9f8458388342139ecce/scripts/3.2.3_assign_secondary_zone.py#L55)
